In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import re
import joblib
import string

In [21]:
fake = pd.read_csv('/Fake.csv')
true = pd.read_csv('/True.csv')

In [22]:
fake.head()

                                               title  ...               date
0   Donald Trump Sends Out Embarrassing New Year’...  ...  December 31, 2017
1   Drunk Bragging Trump Staffer Started Russian ...  ...  December 31, 2017
2   Sheriff David Clarke Becomes An Internet Joke...  ...  December 30, 2017
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...  December 29, 2017
4   Pope Francis Just Called Out Donald Trump Dur...  ...  December 25, 2017

[5 rows x 4 columns]

In [23]:
fake['class'] = 0
true['class'] = 1

In [24]:
data = pd.concat([fake, true], axis = 0)

In [ ]:
data.sample(10)

In [26]:
data = data.drop(["title","subject","date"], axis = 1)

In [27]:
data.reset_index(inplace = True)
data.drop(["index"], axis = 1, inplace = True)

In [28]:
data.sample(5)

                                                    text  class
4536   As we know, the final United Nations General A...      0
1711   Donald Trump is himself, a pervert. We all kne...      0
23219  21st Century Wire saysFollowing a wave of hidd...      0
18088  Kara Young, the biracial model who dated Donal...      0
29840  WASHINGTON (Reuters) - The U.S. House of Repre...      1

In [29]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"['-?]", "", text)
    text = re.sub(r"\W", " ", text)
    text = re.sub(r"https?://\S+|\bwww\.\S+", "", text)
    text = re.sub(r"<.*?>+", "", text)
    text = re.sub(r"[%s]" % re.escape(string.punctuation), "", text)
    text = re.sub(r"\n", "", text)
    text = re.sub(r"\w*\d\w*", "", text)
    return text

In [30]:
data["text"] = data["text"].apply(clean_text)

In [31]:
x = data["text"]
y = data["class"]

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.25,random_state=42)

In [32]:
vectorizer = TfidfVectorizer()
xv_train = vectorizer.fit_transform(xtrain)
xv_test = vectorizer.transform(xtest)

In [33]:
lr = LogisticRegression()
lr.fit(xv_train,ytrain)

LogisticRegression()

In [34]:
prediction = lr.predict(xv_test)
lr.score(xv_test, ytest)

0.9860133630289533

In [35]:
print(classification_report(ytest, prediction))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5895
           1       0.98      0.99      0.99      5330

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225

In [36]:
joblib.dump(vectorizer, 'vectorizer.jb')
joblib.dump(lr, 'lr_model.jb')

['lr_model.jb']

In [46]:
!python Fake detection.py

python3: can't open file '/content/Fake': [Errno 2] No such file or directory